Here I will be talking and working on the preprocessed data for using and applying classification tools


In [6]:
import numpy as np
import pandas as pd
import seaborn as sns
import statsmodels.discrete.discrete_model as snd
from sklearn.metrics import r2_score
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [7]:
data = pd.read_csv('/Users/dikshantthapa/PycharmProjects/pythonProject/Data Files/day2/Classification.csv',header=0)

In [8]:
data.shape
#data.head()

(506, 17)

Since the Data is already a cleaned data i will try to implement the models to predict wheather it is sold in 3 months or not 
and i will be checking the accuracy using the confusion matrix and r2_score

In [25]:
x = data.loc[:,data.columns!='Sold']

In [10]:
x.head()

price  resid_area  air_qual  room_num   age  teachers  poor_prop  \
0   24.0       32.31     0.538     6.575  65.2      24.7       4.98   
1   21.6       37.07     0.469     6.421  78.9      22.2       9.14   
2   34.7       37.07     0.469     7.185  61.1      22.2       4.03   
3   33.4       32.18     0.458     6.998  45.8      21.3       2.94   
4   36.2       32.18     0.458     7.147  54.2      21.3       5.33   

   n_hos_beds  n_hot_rooms  rainfall     parks  avg_dist  airport_YES  \
0       5.480     11.19200        23  0.049347    4.0875            1   
1       7.332     12.17280        42  0.046146    4.9675            0   
2       7.394     46.19856        38  0.045764    4.9675            0   
3       9.268     11.26720        45  0.047151    6.0650            1   
4       8.824     11.28960        55  0.039474    6.0625            0   

   waterbody_Lake  waterbody_Lake and River  waterbody_River  
0               0                         0                1  
1               1                         0                0  
2               0                         0                0  
3               1                         0                0  
4               1                         0                0

In [11]:
y= data['Sold']

In [12]:
X_train,X_test,Y_train,Y_test = train_test_split(x,y,test_size=0.3,random_state=0)

In [13]:
print(X_train.shape,X_test.shape,Y_train.shape,Y_test.shape)

(354, 16) (152, 16) (354,) (152,)


In [14]:
model_multi_logistic = LogisticRegression()

In [25]:
model_multi_logistic.fit(X_train,Y_train)

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [26]:
y_train_result = model_multi_logistic.predict(X_train)

In [27]:
y_test_result = model_multi_logistic.predict(X_test)

In [28]:
r2_score(Y_test,y_test_result)

-0.43677545924736916

In [29]:
r2_score(Y_train,y_train_result)

-0.3489384866630376

In [30]:
model_multi_stat = snd.Logit(Y_train,X_train).fit()

Optimization terminated successfully.
         Current function value: 0.547436
         Iterations 6


In [31]:
Y_train_stats = model_multi_stat.predict(X_train)

In [32]:
Y_test_stats = model_multi_stat.predict(X_test)

In [33]:
model_multi_stat.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                   Sold   No. Observations:                  354
Model:                          Logit   Df Residuals:                      338
Method:                           MLE   Df Model:                           15
Date:                Tue, 25 Apr 2023   Pseudo R-squ.:                  0.2084
Time:                        23:48:10   Log-Likelihood:                -193.79
converged:                       True   LL-Null:                       -244.81
Covariance Type:            nonrobust   LLR p-value:                 5.366e-15
============================================================================================
                               coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------
price                       -0.2936      0.042     -7.058      0.000      -0.375      -0.212
resid_area                  -0.0069      0.028     -0.251      0.802      -0.061       0.047
air_qual                    -9.3536      3.280     -2.851      0.004     -15.783      -2.924
room_num                     1.2731      0.295      4.319      0.000       0.695       1.851
age                         -0.0074      0.008     -0.870      0.384      -0.024       0.009
teachers                     0.2725      0.069      3.955      0.000       0.137       0.407
poor_prop                   -0.1936      0.040     -4.831      0.000      -0.272      -0.115
n_hos_beds                   0.2765      0.086      3.224      0.001       0.108       0.445
n_hot_rooms                 -0.0670      0.052     -1.295      0.195      -0.168       0.034
rainfall                    -0.0087      0.010     -0.854      0.393      -0.029       0.011
parks                       38.3610     29.731      1.290      0.197     -19.910      96.632
avg_dist                    -0.5808      0.120     -4.832      0.000      -0.816      -0.345
airport_YES                 -0.2237      0.258     -0.867      0.386      -0.730       0.282
waterbody_Lake              -0.0177      0.369     -0.048      0.962      -0.742       0.706
waterbody_Lake and River     0.1447      0.408      0.355      0.723      -0.655       0.944
waterbody_River              0.4856      0.313      1.550      0.121      -0.128       1.100
============================================================================================
"""

In [34]:
model_multi_logistic.predict_proba(X_train)

array([[0.9701716 , 0.0298284 ],
       [0.26160088, 0.73839912],
       [0.5107375 , 0.4892625 ],
       [0.21839366, 0.78160634],
       [0.74957976, 0.25042024],
       [0.72858441, 0.27141559],
       [0.50282803, 0.49717197],
       [0.77052025, 0.22947975],
       [0.30171002, 0.69828998],
       [0.55054049, 0.44945951],
       [0.68192346, 0.31807654],
       [0.4487221 , 0.5512779 ],
       [0.94022373, 0.05977627],
       [0.64926386, 0.35073614],
       [0.28444713, 0.71555287],
       [0.69042797, 0.30957203],
       [0.42221578, 0.57778422],
       [0.36105034, 0.63894966],
       [0.32318279, 0.67681721],
       [0.73229057, 0.26770943],
       [0.2680763 , 0.7319237 ],
       [0.25038136, 0.74961864],
       [0.64896027, 0.35103973],
       [0.2252281 , 0.7747719 ],
       [0.382299  , 0.617701  ],
       [0.81923834, 0.18076166],
       [0.85541212, 0.14458788],
       [0.5763227 , 0.4236773 ],
       [0.44476216, 0.55523784],
       [0.09869216, 0.90130784],
       [0.

In [35]:
y_pp = model_multi_logistic.predict(X_train)

In [36]:
y_ppp = (model_multi_logistic.predict_proba(X_train)[:,1]>= 0.3).astype(bool)

In [38]:
confusion_matrix(Y_train,y_pp)

array([[126,  61],
       [ 58, 109]])

In [15]:
#using the Linear Discriminant Analysis

In [16]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [17]:
lda = LinearDiscriminantAnalysis()

In [19]:
lda.fit(X_train,Y_train)

LinearDiscriminantAnalysis()

In [20]:
y_pred_lda = lda.predict(X_test)

In [21]:
y_pred_lda1 = lda.predict(X_train)

In [22]:
r2_score(Y_test,y_pred_lda)

-0.4638844301765648

In [23]:
r2_score(Y_train,y_pred_lda1)

-0.25825354638316944

In [26]:
Y_a = lda.predict(x)

In [31]:
confusion_matrix(y,Y_a)

array([[188,  88],
       [ 77, 153]])